package org.openmrs.module.pharmacy.enumerations;

public enum OperationType {
    DISPENSATION,
    DISTRIBUTION,
    RECEPTION,
    RECEPTION_PRODUCT_BACK,
    INVENTORY,
    SITE_PRODUCT_BACK,
    TRANSFER_IN,
    TRANSFER_OUT,
    DONATION,
    POSITIVE_INVENTORY_ADJUSTMENT,
    OTHER_LOST,
    THIEF,
    NEGATIVE_INVENTORY_ADJUSTMENT,
    EXPIRED_PRODUCT,
    SPOILED_PRODUCT,
    DESTROYED
}
